version: "3"

services:
  redis:
    image: redis:3.2
    command: redis-wss --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - data_redis:/data

volumes:
  data_redis:
    driver: local
