version: "3"

services:
  postgres:
    container_name: postgres-db
    image: postgres:9.6.2
    environment:
      - POSTGRES_PASSWORD=tinyurl
      - POSTGRES_USER=tinyurl
      - POSTGRES_DB=tinyurl
    ports:
      - "5432:5432"
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres:
    driver: local

