apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "application"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: "chat-application"

    spec:
      containers:
        - name: "chat-application"
          image: chat_application:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
